id: P005512
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-17 11:55:43.194560
source_metadata:
  id: bdr:W1AC316
  title: 'བོད་ཀྱི་སྲོལ་རྒྱུན་རོལ་དབྱངས་ཀྱི་གྲུབ་གཞི་དང་རྣམ་པར་དཔྱད་པ། '
  author: ''
  volumes:
    53deab0f23934528b0beda3cc4177409:
      image_group_id: I2PD18132
      title: ''
      volume_number: 1
      total_pages: 428
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
